In [1]:
import torch
from torch.nn.utils.rnn import pad_packed_sequence,pack_padded_sequence

In [9]:
ori_a = [[1],[2,3,4],[5,6],[7,8,9,9]]

In [2]:
a = [[1,0,0,0],[2,3,4,0],[5,6,0,0],[7,8,9,9]]

In [18]:
ori_len = torch.tensor([len(i) for i in ori_a])

In [19]:
t_a = torch.tensor(a)

In [20]:
t_a

tensor([[1, 0, 0, 0],
        [2, 3, 4, 0],
        [5, 6, 0, 0],
        [7, 8, 9, 9]])

In [22]:
lengths, idx = ori_len.sort(0,descending=True)

In [23]:
lengths, idx

(tensor([4, 3, 2, 1]), tensor([3, 1, 2, 0]))

In [26]:
_, un_idx = idx.sort(0)

In [34]:
embeded = torch.nn.Embedding(20,2,padding_idx=0)
lstm = torch.nn.LSTM(2,6,batch_first = True)

In [28]:
t_a[idx]

tensor([[7, 8, 9, 9],
        [2, 3, 4, 0],
        [5, 6, 0, 0],
        [1, 0, 0, 0]])

In [36]:
embed_a = embeded(t_a[idx])

In [37]:
embed_a

tensor([[[-0.5365,  0.0707],
         [ 0.6974, -0.2787],
         [ 2.1905, -0.5927],
         [ 2.1905, -0.5927]],

        [[-0.2537,  1.6083],
         [-0.3243,  0.1823],
         [-1.2489,  1.5352],
         [ 0.0000,  0.0000]],

        [[ 0.0273, -0.3106],
         [ 0.2029, -0.9987],
         [ 0.0000,  0.0000],
         [ 0.0000,  0.0000]],

        [[-2.0155,  0.1443],
         [ 0.0000,  0.0000],
         [ 0.0000,  0.0000],
         [ 0.0000,  0.0000]]], grad_fn=<EmbeddingBackward>)

In [41]:
pack_a = pack_padded_sequence(embed_a,lengths=lengths,batch_first=True)

In [42]:
pack_a 

PackedSequence(data=tensor([[-0.5365,  0.0707],
        [-0.2537,  1.6083],
        [ 0.0273, -0.3106],
        [-2.0155,  0.1443],
        [ 0.6974, -0.2787],
        [-0.3243,  0.1823],
        [ 0.2029, -0.9987],
        [ 2.1905, -0.5927],
        [-1.2489,  1.5352],
        [ 2.1905, -0.5927]], grad_fn=<PackPaddedSequenceBackward>), batch_sizes=tensor([4, 3, 2, 1]), sorted_indices=None, unsorted_indices=None)

In [44]:
out,(h,c) = lstm(pack_a)

In [46]:
out,h,c

(PackedSequence(data=tensor([[-0.1264,  0.0231,  0.1045,  0.0552, -0.1137, -0.0125],
         [-0.1538, -0.0713, -0.0403,  0.0373, -0.0287,  0.1058],
         [-0.0531,  0.0181,  0.1258,  0.0332, -0.1597, -0.0647],
         [-0.2451,  0.1371,  0.1397,  0.0854, -0.0622,  0.1171],
         [-0.0385, -0.0139,  0.1493,  0.0266, -0.2300, -0.0930],
         [-0.2070, -0.0452,  0.0643,  0.0702, -0.1230,  0.0269],
         [-0.0036,  0.0752,  0.2717,  0.0495, -0.2837, -0.1184],
         [ 0.1800, -0.0667,  0.1572, -0.0713, -0.3532, -0.1547],
         [-0.3335, -0.0645,  0.0170,  0.1089, -0.0462,  0.2221],
         [ 0.2937, -0.1103,  0.1748, -0.1224, -0.4024, -0.1929]],
        grad_fn=<CatBackward>), batch_sizes=tensor([4, 3, 2, 1]), sorted_indices=None, unsorted_indices=None),
 tensor([[[ 0.2937, -0.1103,  0.1748, -0.1224, -0.4024, -0.1929],
          [-0.3335, -0.0645,  0.0170,  0.1089, -0.0462,  0.2221],
          [-0.0036,  0.0752,  0.2717,  0.0495, -0.2837, -0.1184],
          [-0.2451, 

In [53]:
pad_a, _ = pad_packed_sequence(out,batch_first=True)

In [54]:
pad_a

tensor([[[-0.1264,  0.0231,  0.1045,  0.0552, -0.1137, -0.0125],
         [-0.0385, -0.0139,  0.1493,  0.0266, -0.2300, -0.0930],
         [ 0.1800, -0.0667,  0.1572, -0.0713, -0.3532, -0.1547],
         [ 0.2937, -0.1103,  0.1748, -0.1224, -0.4024, -0.1929]],

        [[-0.1538, -0.0713, -0.0403,  0.0373, -0.0287,  0.1058],
         [-0.2070, -0.0452,  0.0643,  0.0702, -0.1230,  0.0269],
         [-0.3335, -0.0645,  0.0170,  0.1089, -0.0462,  0.2221],
         [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000]],

        [[-0.0531,  0.0181,  0.1258,  0.0332, -0.1597, -0.0647],
         [-0.0036,  0.0752,  0.2717,  0.0495, -0.2837, -0.1184],
         [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000]],

        [[-0.2451,  0.1371,  0.1397,  0.0854, -0.0622,  0.1171],
         [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
         [ 0.0000, 

In [55]:
torch.index_select(pad_a, 0, un_idx)

tensor([[[-0.2451,  0.1371,  0.1397,  0.0854, -0.0622,  0.1171],
         [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000]],

        [[-0.1538, -0.0713, -0.0403,  0.0373, -0.0287,  0.1058],
         [-0.2070, -0.0452,  0.0643,  0.0702, -0.1230,  0.0269],
         [-0.3335, -0.0645,  0.0170,  0.1089, -0.0462,  0.2221],
         [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000]],

        [[-0.0531,  0.0181,  0.1258,  0.0332, -0.1597, -0.0647],
         [-0.0036,  0.0752,  0.2717,  0.0495, -0.2837, -0.1184],
         [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000]],

        [[-0.1264,  0.0231,  0.1045,  0.0552, -0.1137, -0.0125],
         [-0.0385, -0.0139,  0.1493,  0.0266, -0.2300, -0.0930],
         [ 0.1800, -0.0667,  0.1572, -0.0713, -0.3532, -0.1547],
         [ 0.2937, 